// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: core/worker/protos/worker.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkerStatus int32

const (
	WorkerStatus_idle WorkerStatus = 0
	WorkerStatus_busy WorkerStatus = 1
)

// Enum value maps for WorkerStatus.
var (
	WorkerStatus_name = map[int32]string{
		0: "idle",
		1: "busy",
	}
	WorkerStatus_value = map[string]int32{
		"idle": 0,
		"busy": 1,
	}
)

func (x WorkerStatus) Enum() *WorkerStatus {
	p := new(WorkerStatus)
	*p = x
	return p
}

func (x WorkerStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_core_worker_protos_worker_proto_enumTypes[0].Descriptor()
}

func (WorkerStatus) Type() protoreflect.EnumType {
	return &file_core_worker_protos_worker_proto_enumTypes[0]
}

func (x WorkerStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerStatus.Descriptor instead.
func (WorkerStatus) EnumDescriptor() ([]byte, []int) {
	return file_core_worker_protos_worker_proto_rawDescGZIP(), []int{0}
}

type WorkerEvent int32

const (
	WorkerEvent_getstatus WorkerEvent = 0
	WorkerEvent_dispatch  WorkerEvent = 1
)

// Enum value maps for WorkerEvent.
var (
	WorkerEvent_name = map[int32]string{
		0: "getstatus",
		1: "dispatch",
	}
	WorkerEvent_value = map[string]int32{
		"getstatus": 0,
		"dispatch":  1,
	}
)

func (x WorkerEvent) Enum() *WorkerEvent {
	p := new(WorkerEvent)
	*p = x
	return p
}

func (x WorkerEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkerEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_core_worker_protos_worker_proto_enumTypes[1].Descriptor()
}

func (WorkerEvent) Type() protoreflect.EnumType {
	return &file_core_worker_protos_worker_proto_enumTypes[1]
}

func (x WorkerEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkerEvent.Descriptor instead.
func (WorkerEvent) EnumDescriptor() ([]byte, []int) {
	return file_core_worker_protos_worker_proto_rawDescGZIP(), []int{1}
}

type WorkerReqStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event WorkerEvent `protobuf:"varint,1,opt,name=event,proto3,enum=worker.WorkerEvent" json:"event,omitempty"`
	Data  []byte      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *WorkerReqStruct) Reset() {
	*x = WorkerReqStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_worker_protos_worker_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerReqStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerReqStruct) ProtoMessage() {}

func (x *WorkerReqStruct) ProtoReflect() protoreflect.Message {
	mi := &file_core_worker_protos_worker_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerReqStruct.ProtoReflect.Descriptor instead.
func (*WorkerReqStruct) Descriptor() ([]byte, []int) {
	return file_core_worker_protos_worker_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerReqStruct) GetEvent() WorkerEvent {
	if x != nil {
		return x.Event
	}
	return WorkerEvent_getstatus
}

func (x *WorkerReqStruct) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type WorkerResStruct struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Event  WorkerEvent  `protobuf:"varint,1,opt,name=event,proto3,enum=worker.WorkerEvent" json:"event,omitempty"`
	Status WorkerStatus `protobuf:"varint,2,opt,name=status,proto3,enum=worker.WorkerStatus" json:"status,omitempty"`
	Data   []byte       `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *WorkerResStruct) Reset() {
	*x = WorkerResStruct{}
	if protoimpl.UnsafeEnabled {
		mi := &file_core_worker_protos_worker_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WorkerResStruct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerResStruct) ProtoMessage() {}

func (x *WorkerResStruct) ProtoReflect() protoreflect.Message {
	mi := &file_core_worker_protos_worker_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerResStruct.ProtoReflect.Descriptor instead.
func (*WorkerResStruct) Descriptor() ([]byte, []int) {
	return file_core_worker_protos_worker_proto_rawDescGZIP(), []int{1}
}

func (x *WorkerResStruct) GetEvent() WorkerEvent {
	if x != nil {
		return x.Event
	}
	return WorkerEvent_getstatus
}

func (x *WorkerResStruct) GetStatus() WorkerStatus {
	if x != nil {
		return x.Status
	}
	return WorkerStatus_idle
}

func (x *WorkerResStruct) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_core_worker_protos_worker_proto protoreflect.FileDescriptor

var file_core_worker_protos_worker_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x06, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x22, 0x50, 0x0a, 0x0f, 0x57, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x52, 0x65, 0x71, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x29, 0x0a, 0x05,
	0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e, 0x77, 0x6f,
	0x72, 0x6b, 0x65, 0x72, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x7e, 0x0a, 0x0f, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x12, 0x29,
	0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x13, 0x2e,
	0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x45, 0x76, 0x65,
	0x6e, 0x74, 0x52, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x2c, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x2a, 0x22, 0x0a, 0x0c, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08, 0x0a, 0x04, 0x69,
	0x64, 0x6c, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x62, 0x75, 0x73, 0x79, 0x10, 0x01, 0x2a,
	0x2a, 0x0a, 0x0b, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0d,
	0x0a, 0x09, 0x67, 0x65, 0x74, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x10, 0x00, 0x12, 0x0c, 0x0a,
	0x08, 0x64, 0x69, 0x73, 0x70, 0x61, 0x74, 0x63, 0x68, 0x10, 0x01, 0x32, 0x54, 0x0a, 0x0a, 0x57,
	0x6f, 0x72, 0x6b, 0x65, 0x72, 0x47, 0x52, 0x50, 0x43, 0x12, 0x46, 0x0a, 0x0c, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x12, 0x17, 0x2e, 0x77, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x2e, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x52, 0x65, 0x73, 0x53, 0x74, 0x72, 0x75,
	0x63, 0x74, 0x1a, 0x17, 0x2e, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x2e, 0x57, 0x6f, 0x72, 0x6b,
	0x65, 0x72, 0x52, 0x65, 0x71, 0x53, 0x74, 0x72, 0x75, 0x63, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30,
	0x01, 0x42, 0x37, 0x5a, 0x35, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x77, 0x61, 0x6e, 0x67, 0x79, 0x75, 0x63, 0x68, 0x65, 0x2f, 0x77, 0x6f, 0x72, 0x6b, 0x65, 0x72,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x63, 0x6f, 0x72, 0x65, 0x2f, 0x77, 0x6f, 0x72,
	0x6b, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_core_worker_protos_worker_proto_rawDescOnce sync.Once
	file_core_worker_protos_worker_proto_rawDescData = file_core_worker_protos_worker_proto_rawDesc
)

func file_core_worker_protos_worker_proto_rawDescGZIP() []byte {
	file_core_worker_protos_worker_proto_rawDescOnce.Do(func() {
		file_core_worker_protos_worker_proto_rawDescData = protoimpl.X.CompressGZIP(file_core_worker_protos_worker_proto_rawDescData)
	})
	return file_core_worker_protos_worker_proto_rawDescData
}

var file_core_worker_protos_worker_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_core_worker_protos_worker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_core_worker_protos_worker_proto_goTypes = []interface{}{
	(WorkerStatus)(0),       // 0: worker.WorkerStatus
	(WorkerEvent)(0),        // 1: worker.WorkerEvent
	(*WorkerReqStruct)(nil), // 2: worker.WorkerReqStruct
	(*WorkerResStruct)(nil), // 3: worker.WorkerResStruct
}
var file_core_worker_protos_worker_proto_depIdxs = []int32{
	1, // 0: worker.WorkerReqStruct.event:type_name -> worker.WorkerEvent
	1, // 1: worker.WorkerResStruct.event:type_name -> worker.WorkerEvent
	0, // 2: worker.WorkerResStruct.status:type_name -> worker.WorkerStatus
	3, // 3: worker.WorkerGRPC.StreamWorker:input_type -> worker.WorkerResStruct
	2, // 4: worker.WorkerGRPC.StreamWorker:output_type -> worker.WorkerReqStruct
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_core_worker_protos_worker_proto_init() }
func file_core_worker_protos_worker_proto_init() {
	if File_core_worker_protos_worker_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_core_worker_protos_worker_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerReqStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_core_worker_protos_worker_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WorkerResStruct); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_core_worker_protos_worker_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_worker_protos_worker_proto_goTypes,
		DependencyIndexes: file_core_worker_protos_worker_proto_depIdxs,
		EnumInfos:         file_core_worker_protos_worker_proto_enumTypes,
		MessageInfos:      file_core_worker_protos_worker_proto_msgTypes,
	}.Build()
	File_core_worker_protos_worker_proto = out.File
	file_core_worker_protos_worker_proto_rawDesc = nil
	file_core_worker_protos_worker_proto_goTypes = nil
	file_core_worker_protos_worker_proto_depIdxs = nil
}
